# Generated by Django 4.2.4 on 2023-08-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randoms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='amout',
            new_name='amount',
        ),
    ]
