# Generated by Django 4.2.4 on 2023-08-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activationcode',
            options={'ordering': ('-id',), 'verbose_name': ('Код',), 'verbose_name_plural': 'Коды активации'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amout',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='activationcode',
            name='datetime_created',
            field=models.DateTimeField(auto_created=True, verbose_name='дата создания'),
        ),
    ]
