# Generated by Django 4.2.4 on 2023-08-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_activationcode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_filled',
            field=models.BooleanField(default=False, verbose_name='пополнение?'),
        ),
    ]
